export {
  BOOKING_PERIODS,
  BOOKING_RESULT_MODES,
  BOOKING_SEARCH_WINDOW_DAYS,
  BOOKING_TIME_ZONE,
  BOOKING_WEEKDAYS,
  MAX_BOOKING_OPTIONS,
  MAX_DAY_SLOT_OPTIONS,
  OCCUPYING_APPOINTMENT_STATUSES,
} from "./ai-booking.constants.js";
export {
  addIsoDateDays,
  findAppointmentAvailability,
  getCasablancaIsoDate,
  getCasablancaIsoTime,
  type BookingAppointment,
  type BookingResource,
  type BookingSchedule,
  type BookingWeekday,
  type BookingWorkshop,
  type DirectusBookingAvailabilitySnapshot,
} from "./ai-booking.availability.js";
export {
  checkBookingSlotAvailability,
  type BookingSlotCheckResult,
  type BookingSlotSelection,
} from "./ai-booking.confirmation.js";
export {
  AppointmentConfirmationRequestSchema,
  AppointmentConfirmationResultSchema,
  AppointmentAvailabilityOptionSchema,
  AppointmentAvailabilityResultSchema,
  BookingServiceTypeSchema,
  BookingIdempotencyKeySchema,
  BookingShowroomSchema,
  BookingVehicleIdSchema,
  BookingTimeZoneSchema,
  IsoDateSchema,
  IsoDateTimeSchema,
  IsoTimeSchema,
  SecuredAppointmentAvailabilityOptionSchema,
  SecuredAppointmentAvailabilityResultSchema,
  createAppointmentAvailabilityRequestSchema,
  isValidIsoDate,
  type AppointmentAvailabilityOption,
  type AppointmentAvailabilityRequest,
  type AppointmentAvailabilityResult,
  type AppointmentConfirmationRequest,
  type AppointmentConfirmationResult,
  type BookingServiceType,
  type BookingShowroom,
  type SecuredAppointmentAvailabilityOption,
  type SecuredAppointmentAvailabilityResult,
} from "./ai-booking.schema.js";
