export {
  CRC_APPOINTMENT_QUEUES,
  CRC_APPOINTMENT_STATUSES,
  CrcAppointmentIdParameterSchema,
  CrcAppointmentIdSchema,
  CrcAppointmentListQuerySchema,
  CrcAppointmentListSchema,
  CrcAppointmentQueueSchema,
  CrcAppointmentSchema,
  CrcAppointmentStatusSchema,
  type CrcAppointment,
  type CrcAppointmentListQuery,
  type CrcAppointmentQueue,
  type CrcAppointmentStatus,
} from "./crc-appointment.schema.js";
