export {
  CRC_APPOINTMENT_ACTIONS,
  CRC_APPOINTMENT_QUEUES,
  CRC_APPOINTMENT_STATUSES,
  CRC_REJECTION_REASON_CODES,
  CrcAppointmentActionResultSchema,
  CrcAppointmentActionSchema,
  CrcCallbackActionBodySchema,
  CrcConfirmActionBodySchema,
  CrcAppointmentIdParameterSchema,
  CrcAppointmentIdSchema,
  CrcIdempotencyKeySchema,
  CrcAppointmentListQuerySchema,
  CrcAppointmentListSchema,
  CrcAppointmentQueueSchema,
  CrcRejectActionBodySchema,
  CrcRejectionReasonCodeSchema,
  CrcAppointmentSchema,
  CrcAppointmentStatusSchema,
  type CrcAppointment,
  type CrcAppointmentAction,
  type CrcAppointmentActionResult,
  type CrcCallbackActionBody,
  type CrcConfirmActionBody,
  type CrcAppointmentListQuery,
  type CrcAppointmentQueue,
  type CrcRejectActionBody,
  type CrcRejectionReasonCode,
  type CrcAppointmentStatus,
} from "./crc-appointment.schema.js";
